name: "homepedia"
version: "1.0.0"
config-version: 2

profile: "homepedia"

model-paths: ["models"]
test-paths: ["tests"]

models:
  homepedia:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table

