apiVersion: 1

datasources:
  - name: Homepedia PostgreSQL
    uid: homepedia-postgres
    type: postgres
    access: proxy
    url: postgres:5432
    user: homepedia
    isDefault: true
    secureJsonData:
      password: homepedia
    jsonData:
      database: homepedia
      sslmode: disable
      postgresVersion: 1600
      maxOpenConns: 10
